// overload 0
ARRAY TEXT($arrColNames1;0)
ARRAY TEXT($arrHeaderNames2;0)
ARRAY POINTER($arrColVars3;0)
ARRAY POINTER($arrHeaderVars4;0)
ARRAY BOOLEAN($arrColsVisible5;0)
ARRAY POINTER($arrStyles6;0)
ARRAY TEXT($arrFooterNames7;0)
ARRAY POINTER($arrFooterVars8;0)
LISTBOX GET ARRAYS(*;"synthText";$arrColNames1;$arrHeaderNames2;$arrColVars3;$arrHeaderVars4;$arrColsVisible5;$arrStyles6;$arrFooterNames7;$arrFooterVars8)
// overload 1
var $object9 : Variant
ARRAY TEXT($arrColNames10;0)
ARRAY TEXT($arrHeaderNames11;0)
ARRAY POINTER($arrColVars12;0)
ARRAY POINTER($arrHeaderVars13;0)
ARRAY BOOLEAN($arrColsVisible14;0)
ARRAY POINTER($arrStyles15;0)
ARRAY TEXT($arrFooterNames16;0)
ARRAY POINTER($arrFooterVars17;0)
LISTBOX GET ARRAYS($object9;$arrColNames10;$arrHeaderNames11;$arrColVars12;$arrHeaderVars13;$arrColsVisible14;$arrStyles15;$arrFooterNames16;$arrFooterVars17)
